[profile.default]
fs_permissions = [
  { access = "readwrite", path = "./addresses" },
  { access = "read", path = "./chainConfigs" },
  { access = "read", path = "./package.json" },
  { access = "readwrite", path = "./deterministicConfig" },
]
libs = ['node_modules', 'script']
auto_detect_solc = true
fuzz_runs = 500
optimizer = true
optimizer_runs = 500000
out = 'out'
script = 'script'
src = 'src'
solc_version = '0.8.20'
via_ir = true

[profile.dev]
optimizer = false
optimizer_runs = 0
via_ir = false

