[profile.default]
src = "src"
out = "out"
libs = ["node_modules"]
via_ir = true
solc_version = '0.8.28'
evm_version = 'cancun'
optimizer = true
optimizer_runs = 1_000_000
fs_permissions = [
  { access = "readwrite", path = "./addresses" },
  { access = "read", path = "./package.json" },
  { access = "readwrite", path = "./deterministicConfig" },
  { access = "read", path = "../shared-contracts/chainConfigs" },
  { access = "readwrite", path = "../shared-contracts/deterministicConfig" }
]

[profile.dev]
optimizer = false
optimizer_runs = 0
via_ir = true

[rpc_endpoints]
sepolia = "https://eth-sepolia.g.alchemy.com/v2/${ALCHEMY_KEY}"
mainnet = "https://eth-mainnet.g.alchemy.com/v2/${ALCHEMY_KEY}"
base = "https://base-mainnet.g.alchemy.com/v2/${ALCHEMY_KEY}"
base_sepolia = "https://base-sepolia.g.alchemy.com/v2/${ALCHEMY_KEY}"
optimism = "https://opt-mainnet.g.alchemy.com/v2/${ALCHEMY_KEY}"
zora = "https://rpc.zora.energy/${CONDUIT_KEY}"
zora_sepolia = "https://sepolia.rpc.zora.energy/${CONDUIT_KEY}"
arbitrum_one = "https://arb-mainnet.g.alchemy.com/v2/${ALCHEMY_KEY}"
arbitrum_sepolia = "https://arb-sepolia.g.alchemy.com/v2/${ALCHEMY_KEY}"
blast = "https://blast.gateway.tenderly.co/${TENDERLY_KEY}/"
blast_sepolia = "https://sepolia.blast.io"